hackclub/airbridge

- src/utils.js
> Revert "unauthed requests can filter fields"

- src/whitelist.js
added a couple columns specific to the AMAs
> Add AMA fields for pulling into Twitch & Website

- src/whitelist.js
Not 100% sure how this api works but after looking through it a little it seems like Operations and Sessions are suppose to be strings.
> Fix strings

- src/v0.1/airtable-info.yml
https://github.com/hackclub/scrappy/issues/44
> Add Max Streaks Col

- .github/workflows/format.yml
- package.json
- src/v0/allowlist.js
- tests/v0.1/allowlist.test.js
Fix formatting CI. Right now it just writes the changes.
> Fix format ci

- src/v0.1/airtable-info.yml
@MatthewStanciu I think this is why your thing isn't working at https://github.com/hackclub/summer-scrapbook/pull/85
feel free to correct me :)
> Add Streaks Toggled Off

- src/v0.1/airtable-info.yml
> Add Stuff for Scavenger Hunt

- src/index.js
- src/v0.1/index.js
- src/v0.1/utils.js
Allows POST requests that upload to Airtable bases (assuming `authKey` is provided). What do you think?
Some things to look at:
- how does this affect caching?
- did I implement authentication correctly?
> Implement posting via authKey

- src/v0.1/airtable-info.yml
I made this for Zach Day but originally hosted it on my personal fork, want to move it here so nothing breaks.
view https://github.com/hackclub/summer-scrapbook/pull/112 :)
> Add the Emoji CSS 

- .github/workflows/test.yml
GitHub now forces u to do a manual review to allow tests for first time contributors, would we be cool adding this back?
> Allow Tests on PRs

- src/v0.1/airtable-info.yml
This PR adds the new table in the Bank Promotions base.
> Add new Bank promotion

- src/v0.1/airtable-info.yml
This PR adds the domains table in the Bank Promotions base
> Add domains airtable

- src/v0.1/airtable-info.yml
Adds the new apac field to the hackathons table.
> Add apac field to hackathons table

- src/v0.1/airtable-info.yml
> Add hybrid field to hackathons table

- src/v0.1/airtable-info.yml
This is a new field added to Airtable for displaying events on events.hackclub.com.
> Add Approved field for Events

- src/v0.1/airtable-info.yml
Adding YSWS completions count to airbridge for use in [ysws.hackclub.com](ysws.hackclub.com)
> Adding YSWS's to airtable-info.yml v0.1

- src/v0.1/airtable-info.yml
added some fields from the Black Box base to the public 0.1 data.
this is for the Black Box gallery.
> add Black Box data

- src/v0.1/airtable-info.yml
Optimize YSWS fields added for gallery
> Added Optimize

- src/v0.1/airtable-info.yml
This is to fix the failing prod test.
> Fix optimize table names

- src/v0.1/airtable-info.yml
This field doesn't exist in airtable!
> Remove non-existant field from optimize submissions
